# Generated by Django 5.1.7 on 2025-03-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_is_480p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_480p',
        ),
    ]
