# Generated by Django 5.1.7 on 2025-03-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_video_is_480p'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_480p',
            field=models.BooleanField(default=False),
        ),
    ]
